### ISSUE TITLE
Ability to disable decoys / limit to only one decoy at a time

### ISSUE THREAD

**Issue by swhitt** [DuckHunt-discord/DHV2#43]
At the moment decoys are incredibly exploitable. We're using the DuckHunt bot in a (fairly competitive) discord channel for a large city subreddit. The ducks are set to sleep during local sleepytime to make it a bit more fair for the people who sleep during normal hours.

Right now I can wait until 4am and spawn 50 ducks using decoys and then kill them all myself while everyone is in bed. Even without a good clover, superducks make this highly worth it. 

If we could limit decoys to allow only one spawning at a time it would make this much more of a pain to abuse; if not we'd really appreciate it if decoys could just be disabled entirely as a setting.

**Comment by swhitt** [comment]
Limiting spawning to one per person per `$period` might make more sense, where `$period` is 1/4/6/24 hours. Not sure what makes the most balanced approach.

**Comment by swhitt** [comment]
sure but I know that if that's the actual mechanic I will personally abuse the heck out of it. I'd set a timer on my phone to go off every 15 minutes and launch another.

**Comment by Heroesflorian** [comment]
Hmm... with a good clover those decoys surely are exploitable - if you are alone, that is. Otherwise it is a risky business... And with a *bad* clover it is generally not really useful. 

If you have 1 XP clover, then you have a cost of 7 per bullet, 8 per decoy and some (possibly neglegible) for missed shots... that is 15 XP cost per decoy. With 1 XP clover, you get 10 + 1 = 11 XP per duck killed. That's a granted loss of 4 XP, not accounting for misses. The only thing that can make it positive at all are occasional super ducks, which require additional shots (thus higher cost) and most probably explosive ammo to get them done without MANY shots... all in all, if you add misses and equipment cost, you really need a TON of decoys to have any chance of getting enough super ducks to make it worth using at all. And then again, if someone else is online and steals even a few ducks... gone all XP profits... 

So effectively, decoys are ONLY overpowered when you have a very good clover **and** are completely alone, **and** have the time to buy a LOT of them at once. Otherwise, they are risky / lossy / not really worth the effort. 

Thus, as I like having a choice, I am all for options and thus adding an option to disable or limit decoys is okay imho, but I am against generally nerfing decoys as such. 

What I would really like to see as well though, are some thoughts on how decoys could be changed to be less exploitable while at the same time making them less useless for everyone without "perfect conditions".

**Comment by swhitt** [comment]
It's pretty easy to find an alone time when no one else is online, especially for a discord like ours that is regional so everyone is in bed at the same time. I launched something like 50 decoys at once yesterday and 3-4 of them were superducks that made it all worthwhile in the end. Explosive ammo and a silencer helped a lot.

I think at the very least decoys should be disabled while the ducks are sleeping; maybe make disabling them entirely a server-specific setting. On our server at the moment our house rules just don't allow decoys at all and we self-police.

**Comment by Heroesflorian** [comment]
Well, as I said, you need to be alone, have time for a lot of them, and have good clover. On a regional server with no night owls, shift workers or people from different time zones that is perfectly doable if you get decent clover (or are low level and thus have a way cheaper XP/shot cost, but that I neglected above, as for a group of engaged, competitive hunters it won't take long to reach higher levels anyway). 

I just wanted to point out that clovers are not generally OP, just... selectively OP, selectively okay, or even useless... so I would say their overall balancing could be improved - independent of adding a setting to disable/restrict them optionally, which I support for choice is a good thing.
